<a href="https://colab.research.google.com/github/MaddoSaru/Kaggle-Competitions/blob/master/Titanic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Titanic**

**Pre procesado de datos**

In [32]:
# El código consiste en la realización de un modelo que permita verificar si un pasajero del Titanic sobrevive, o no, de acuerdo a sus características

# Survived = 1 --> Sobrevive
# Survived = 0 --> No sobrevive

In [33]:
# Importar librerías y paquetes

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [34]:
# Importar dataset

dataset_train = pd.read_csv("https://raw.githubusercontent.com/MaddoSaru/Kaggle-Competitions/master/Titanic/train.csv", header = 0)
dataset_test = pd.read_csv("https://raw.githubusercontent.com/MaddoSaru/Kaggle-Competitions/master/Titanic/test.csv", header = 0)

In [35]:
# Visualización de dataset de entrenamiento

dataset_train.head()

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [36]:
# Visualización de dataset de prueba

dataset_test.head()

PassengerId  Pclass  ... Cabin Embarked
0          892       3  ...   NaN        Q
1          893       3  ...   NaN        S
2          894       2  ...   NaN        Q
3          895       3  ...   NaN        S
4          896       3  ...   NaN        S

[5 rows x 11 columns]

In [37]:
# Tamaño del dataset de entrenamiento

dataset_train.shape

(891, 12)

In [38]:
# Tamaño del dataset de prueba

dataset_test.shape

(418, 11)

In [39]:
# Búsqueda de datos faltantes en el conjunto de entrenamiento

dataset_train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [40]:
# Búsqueda de datos faltantes en el conjunto de prueba

dataset_test.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [53]:
# Rellenar datos faltantes en conjunto de entrenamiento y prueba

dataset_train["Age"].fillna(value = dataset_train["Age"].mean(), inplace = True)
dataset_test["Age"].fillna(value = dataset_test["Age"].mean(), inplace = True)

dataset_train["Cabin"].fillna(value = "0", inplace = True)
dataset_test["Cabin"].fillna(value = "0", inplace = True)

dataset_train["Embarked"].fillna(value = "N", inplace = True)

dataset_test["Fare"].fillna(value = dataset_test["Fare"].mean(), inplace = True)

In [54]:
dataset_train.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [55]:
dataset_test.isnull().sum()

PassengerId    0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [62]:
# Tratar datos categóricos

from sklearn.preprocessing import OneHotEncoder

onehotencoder = OneHotEncoder()
dataset_train = onehotencoder.fit_transform(dataset_train).toarray()

print(dataset_train)

[[1. 0. 0. ... 0. 0. 1.]
 [0. 1. 1. ... 1. 1. 0.]
 [0. 1. 1. ... 0. 0. 1.]
 ...
 [0. 1. 1. ... 0. 0. 1.]
 [0. 1. 1. ... 1. 1. 0.]
 [0. 1. 1. ... 1. 1. 0.]]


In [ ]:
# Normalización de los datos

from sklearn.preprocessing import StandardScaler

sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test) 

sc_y = StandardScaler()
y_train = sc_y.fit_transform(y_train) 