<a href="https://colab.research.google.com/github/MaddoSaru/Kaggle-Competitions/blob/master/Titanic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Titanic**

**Pre procesado de datos**

In [81]:
# El código consiste en la realización de un modelo que permita verificar si un pasajero del Titanic sobrevive, o no, de acuerdo a sus características

# Survived = 1 --> Sobrevive
# Survived = 0 --> No sobrevive

# Importar librerías y paquetes

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [128]:
# Importar dataset

dataset_train = pd.read_csv("https://raw.githubusercontent.com/MaddoSaru/Kaggle-Competitions/master/Titanic/train.csv", header = 0)
dataset_test = pd.read_csv("https://raw.githubusercontent.com/MaddoSaru/Kaggle-Competitions/master/Titanic/test.csv", header = 0)

In [83]:
# Visualización de dataset de entrenamiento

dataset_train.head()

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

In [84]:
# Visualización de dataset de prueba

dataset_test.head()

PassengerId  Pclass  ... Cabin Embarked
0          892       3  ...   NaN        Q
1          893       3  ...   NaN        S
2          894       2  ...   NaN        Q
3          895       3  ...   NaN        S
4          896       3  ...   NaN        S

[5 rows x 11 columns]

In [85]:
# Tamaño del dataset de entrenamiento

dataset_train.shape

(891, 12)

In [86]:
# Tamaño del dataset de prueba

dataset_test.shape

(418, 11)

In [87]:
# Búsqueda de datos faltantes en el conjunto de entrenamiento

dataset_train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [88]:
# Búsqueda de datos faltantes en el conjunto de prueba

dataset_test.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [89]:
# Rellenar datos faltantes en conjunto de entrenamiento y prueba

dataset_train["Age"].fillna(value = dataset_train["Age"].mean(), inplace = True)
dataset_test["Age"].fillna(value = dataset_test["Age"].mean(), inplace = True)

dataset_train["Cabin"].fillna(value = "0", inplace = True)
dataset_test["Cabin"].fillna(value = "0", inplace = True)

dataset_train["Embarked"].fillna(value = "N", inplace = True)

dataset_test["Fare"].fillna(value = dataset_test["Fare"].mean(), inplace = True)

In [90]:
dataset_train.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [91]:
dataset_test.isnull().sum()

PassengerId    0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [92]:
# Separación de variables

X_train = dataset_train.iloc[:,[2,4,5,9]].values
y_train = dataset_train.iloc[:,1].values

X_test = dataset_test.iloc[:,[1,3,4,8]].values

In [93]:
# Tratar datos categóricos

from sklearn.preprocessing import LabelEncoder

labelencoder = LabelEncoder()
X_train[:,1] = labelencoder.fit_transform(X_train[:,1])

X_test[:,1] = labelencoder.fit_transform(X_test[:,1])

print(X_train)

[[3 1 22.0 7.25]
 [1 0 38.0 71.2833]
 [3 0 26.0 7.925]
 ...
 [3 0 29.69911764705882 23.45]
 [1 1 26.0 30.0]
 [3 1 32.0 7.75]]


In [94]:
# Escalado de variables

from sklearn.preprocessing import StandardScaler

sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)

X_test = sc_X.fit_transform(X_test)

print(X_train)

[[ 0.82737724  0.73769513 -0.5924806  -0.50244517]
 [-1.56610693 -1.35557354  0.63878901  0.78684529]
 [ 0.82737724 -1.35557354 -0.2846632  -0.48885426]
 ...
 [ 0.82737724 -1.35557354  0.         -0.17626324]
 [-1.56610693  0.73769513 -0.2846632  -0.04438104]
 [ 0.82737724  0.73769513  0.17706291 -0.49237783]]


**XGBoost**

In [95]:
# Ajuste del modelo

from xgboost import XGBClassifier
classifier = XGBClassifier()
classifier.fit(X_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [96]:
# Predicción del conjunto de test

y_pred  = classifier.predict(X_test)

print(y_pred)

[0 0 0 0 1 0 1 0 1 0 0 0 1 0 1 1 0 0 1 0 0 0 1 0 1 0 1 0 0 0 0 0 1 1 0 0 1
 0 0 0 0 0 0 1 1 0 0 0 1 0 0 0 1 1 0 0 0 0 0 1 0 0 0 1 1 1 1 0 0 1 1 0 1 0
 1 1 0 1 0 1 1 0 0 0 0 0 1 1 1 1 0 0 1 0 0 0 1 0 1 0 1 0 0 0 1 0 0 0 0 0 0
 1 1 1 1 0 0 1 0 1 1 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0
 0 0 1 0 0 1 0 0 1 1 0 1 1 1 1 0 0 1 0 0 1 0 0 0 0 0 0 1 1 0 1 1 0 0 1 0 1
 0 1 0 0 0 0 0 0 0 1 0 1 1 0 1 0 1 0 1 0 0 1 0 1 0 0 0 0 1 0 0 1 0 1 0 1 0
 1 0 1 1 0 1 0 0 1 1 0 0 0 0 0 0 1 1 1 1 0 0 0 0 1 0 1 1 1 0 1 0 0 0 0 0 1
 0 0 0 1 1 0 0 0 0 1 0 0 0 1 0 0 1 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 1 1 0 1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 1 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 1 1 0 0 0 1 0 1 0 0 0 0 1 1 0 1 0 0 0 1 0
 0 1 0 0 1 1 0 0 0 0 0 0 1 0 0 1 0 0 0 1 0 1 0 0 0 1 0 1 0 0 1 0 1 0 0 0 0
 0 1 1 1 1 1 0 1 0 0 0]


In [97]:
# K-cross validation

from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print(accuracies.mean())
print(accuracies.std())

0.8328589263420725
0.04344155992223397


In [98]:
survivor_bias = y_pred.sum()/y_pred.size

print(survivor_bias*100,"%")

33.97129186602871 %


In [129]:
# Ajustar dataset

dataset_test["Survived"] = y_pred
dataset_test.drop(dataset_test.columns[[1,2,3,4,5,6,7,8,9,10]], axis = 1, inplace = True)
dataset_test.set_index("PassengerId", inplace = True)

In [130]:
# Exportar resultados

from google.colab import files

dataset_test.to_csv('predictions.csv') 
files.download('predictions.csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [131]:
dataset_test.head(20)

Survived
PassengerId          
892                 0
893                 0
894                 0
895                 0
896                 1
897                 0
898                 1
899                 0
900                 1
901                 0
902                 0
903                 0
904                 1
905                 0
906                 1
907                 1
908                 0
909                 0
910                 1
911                 0